# -*- coding: utf-8 -*-
"""Untitled546.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X6qXiJDgIw9uLSe57X4QVCQ2erKjnyN6
"""

import pandas as pd

# upload data from csv
car = pd.read_csv('/content/cardetails.csv')

car.head()

car.isnull().sum()

car.dtypes

car.describe()

car.sort_values(by = 'km_driven')

car.drop([1312], inplace = True)
car.shape

import seaborn as sns

sns.heatmap(car.corr(), annot= True);

car.columns

car['name'].value_counts()

for x in car.columns:
    print('\n', x, '-------\n', car[x].value_counts())

car.name.unique()

brand_name = []
for x in car.name:
    y = x.split(' ')
    brand_name.append(y[0])

brand_name[:10]

#we can drop the previous column that had the full name
car = car.drop(['name'], axis = 1)

#and add the new column that just has the brand name
car['brand_name'] = brand_name

car.brand_name.value_counts()

car_dummies = pd.get_dummies(car, drop_first = True)

car_dummies.head()

car_dummies.shape